wandb_version: 1

epochs:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725385778
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 71
      - 98
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      6: 4.33.1
      8:
      - 5
      13: linux-x86_64
